import { RankSymbol } from '../types/RankSymbol.type'

const imageList = {
  '2H': require('../../app/assets/cards/2H.png'),
  '3H': require('../../app/assets/cards/3H.png'),
  '4H': require('../../app/assets/cards/4H.png'),
  '5H': require('../../app/assets/cards/5H.png'),
  '6H': require('../../app/assets/cards/6H.png'),
  '7H': require('../../app/assets/cards/7H.png'),
  '8H': require('../../app/assets/cards/8H.png'),
  '9H': require('../../app/assets/cards/9H.png'),
  TH: require('../../app/assets/cards/TH.png'),
  JH: require('../../app/assets/cards/JH.png'),
  QH: require('../../app/assets/cards/QH.png'),
  KH: require('../../app/assets/cards/KH.png'),
  AH: require('../../app/assets/cards/AH.png'),
  '2D': require('../../app/assets/cards/2D.png'),
  '3D': require('../../app/assets/cards/3D.png'),
  '4D': require('../../app/assets/cards/4D.png'),
  '5D': require('../../app/assets/cards/5D.png'),
  '6D': require('../../app/assets/cards/6D.png'),
  '7D': require('../../app/assets/cards/7D.png'),
  '8D': require('../../app/assets/cards/8D.png'),
  '9D': require('../../app/assets/cards/9D.png'),
  TD: require('../../app/assets/cards/TD.png'),
  JD: require('../../app/assets/cards/JD.png'),
  QD: require('../../app/assets/cards/QD.png'),
  KD: require('../../app/assets/cards/KD.png'),
  AD: require('../../app/assets/cards/AD.png'),
  '2S': require('../../app/assets/cards/2S.png'),
  '3S': require('../../app/assets/cards/3S.png'),
  '4S': require('../../app/assets/cards/4S.png'),
  '5S': require('../../app/assets/cards/5S.png'),
  '6S': require('../../app/assets/cards/6S.png'),
  '7S': require('../../app/assets/cards/7S.png'),
  '8S': require('../../app/assets/cards/8S.png'),
  '9S': require('../../app/assets/cards/9S.png'), //
  TS: require('../../app/assets/cards/TS.png'),
  JS: require('../../app/assets/cards/JS.png'),
  QS: require('../../app/assets/cards/QS.png'),
  KS: require('../../app/assets/cards/KS.png'),
  AS: require('../../app/assets/cards/AS.png'),
  '2C': require('../../app/assets/cards/2C.png'),
  '3C': require('../../app/assets/cards/3C.png'),
  '4C': require('../../app/assets/cards/4C.png'),
  '5C': require('../../app/assets/cards/5C.png'),
  '6C': require('../../app/assets/cards/6C.png'),
  '7C': require('../../app/assets/cards/7C.png'),
  '8C': require('../../app/assets/cards/8C.png'),
  '9C': require('../../app/assets/cards/9C.png'),
  TC: require('../../app/assets/cards/TC.png'),
  JC: require('../../app/assets/cards/JC.png'),
  QC: require('../../app/assets/cards/QC.png'),
  KC: require('../../app/assets/cards/KC.png'),
  AC: require('../../app/assets/cards/AC.png'),
}

export const getImage = (rankSymbol: RankSymbol) => {
  return imageList[rankSymbol]
}
