export const GOOGLE_ADMOB_MAINVIEW_BANNER_ID: string =
	process.env.EXPO_PUBLIC_GOOGLE_ADMOB_MAINVIEW_BANNER_ID!
export const GOOGLE_ADMOB_STARTVIEW_BANNER_ID: string =
	process.env.EXPO_PUBLIC_GOOGLE_ADMOB_STARTVIEW_BANNER_ID!
