/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { RankSymbol } from "../../types/RankSymbol.type";

const imageList = {
  "2H": require("../../../assets/cards/2H.png"),
  "3H": require("../../../assets/cards/3H.png"),
  "4H": require("../../../assets/cards/4H.png"),
  "5H": require("../../../assets/cards/5H.png"),
  "6H": require("../../../assets/cards/6H.png"),
  "7H": require("../../../assets/cards/7H.png"),
  "8H": require("../../../assets/cards/8H.png"),
  "9H": require("../../../assets/cards/9H.png"),
  TH: require("../../../assets/cards/TH.png"),
  JH: require("../../../assets/cards/JH.png"),
  QH: require("../../../assets/cards/QH.png"),
  KH: require("../../../assets/cards/KH.png"),
  AH: require("../../../assets/cards/AH.png"),
  "2D": require("../../../assets/cards/2D.png"),
  "3D": require("../../../assets/cards/3D.png"),
  "4D": require("../../../assets/cards/4D.png"),
  "5D": require("../../../assets/cards/5D.png"),
  "6D": require("../../../assets/cards/6D.png"),
  "7D": require("../../../assets/cards/7D.png"),
  "8D": require("../../../assets/cards/8D.png"),
  "9D": require("../../../assets/cards/9D.png"),
  TD: require("../../../assets/cards/TD.png"),
  JD: require("../../../assets/cards/JD.png"),
  QD: require("../../../assets/cards/QD.png"),
  KD: require("../../../assets/cards/KD.png"),
  AD: require("../../../assets/cards/AD.png"),
  "2S": require("../../../assets/cards/2S.png"),
  "3S": require("../../../assets/cards/3S.png"),
  "4S": require("../../../assets/cards/4S.png"),
  "5S": require("../../../assets/cards/5S.png"),
  "6S": require("../../../assets/cards/6S.png"),
  "7S": require("../../../assets/cards/7S.png"),
  "8S": require("../../../assets/cards/8S.png"),
  "9S": require("../../../assets/cards/9S.png"), //
  TS: require("../../../assets/cards/TS.png"),
  JS: require("../../../assets/cards/JS.png"),
  QS: require("../../../assets/cards/QS.png"),
  KS: require("../../../assets/cards/KS.png"),
  AS: require("../../../assets/cards/AS.png"),
  "2C": require("../../../assets/cards/2C.png"),
  "3C": require("../../../assets/cards/3C.png"),
  "4C": require("../../../assets/cards/4C.png"),
  "5C": require("../../../assets/cards/5C.png"),
  "6C": require("../../../assets/cards/6C.png"),
  "7C": require("../../../assets/cards/7C.png"),
  "8C": require("../../../assets/cards/8C.png"),
  "9C": require("../../../assets/cards/9C.png"),
  TC: require("../../../assets/cards/TC.png"),
  JC: require("../../../assets/cards/JC.png"),
  QC: require("../../../assets/cards/QC.png"),
  KC: require("../../../assets/cards/KC.png"),
  AC: require("../../../assets/cards/AC.png"),
};

export const getImage = (rankSymbol: RankSymbol) => {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-return
  return imageList[rankSymbol];
};
